### ISSUE TITLE
architecture changed from arm64 to arm

### ISSUE THREAD

**Issue by ghost** [Galaxy-MSM8916/android_device_samsung_j53gxx#4]
LineageOS 16.0 was arm64, but LineageOS 17.1 became arm, I've noticed it while installing Open GApps

**Comment by zakaryan2004** [comment]
No such thing.

**Comment by ghost** [comment]
But why arm64 GApps installed on 16.0, but failed to install on 17.1?

**Comment by zakaryan2004** [comment]
I don't know, maybe you are confusing devices, but j53gxx never had an arm64 ROM, and an arm64 GApps would never install on it. If it did, then one of those things may have happened:
1. It was actually arm, but you thought it's arm64
2. You were not installing it on j53gxx.
3. The device didn't boot after flashing arm64 gapps.

In any case, just flash arm gapps. Architecture didn't change. It was always arm.

**Comment by ghost** [comment]
yes, device didn't boot after flashing arm64 gapps, I guess it got installed by error
